# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcConfigRemote(wx.Dialog):
#!XRCED:begin-block:xrcConfigRemote.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcConfigRemote.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "ConfigRemote")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    configremote_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="ConfigRemote">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <object class="sizeritem">
            <object class="wxFlexGridSizer">
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>User Name :</label>
                </object>
                <option>1</option>
                <border>0</border>
              </object>
              <object class="sizeritem">
                <object class="wxComboBox" name="user">
                  <selection>0</selection>
                  <value>ishikura</value>
                </object>
                <option>1</option>
                <flag>wxALL|wxEXPAND</flag>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Remote Host : </label>
                </object>
                <border>0</border>
              </object>
              <object class="sizeritem">
                <object class="wxComboBox" name="host">
                  <value>133.66.117.139</value>
                </object>
                <option>1</option>
                <flag>wxALL|wxEXPAND</flag>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Password :</label>
                </object>
                <border>0</border>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="passwd">
                  <style>wxTE_PASSWORD</style>
                </object>
                <flag>wxEXPAND</flag>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Port :</label>
                </object>
                <border>0</border>
              </object>
              <object class="sizeritem">
                <object class="wxComboBox" name="port">
                  <value>22</value>
                  <enabled>0</enabled>
                </object>
              </object>
              <cols>2</cols>
              <rows>5</rows>
              <vgap>5</vgap>
              <hgap>20</hgap>
            </object>
            <option>1</option>
            <flag>wxALL|wxEXPAND</flag>
            <border>5</border>
          </object>
          <label>SSH remote access setting</label>
          <orient>wxVERTICAL</orient>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>3</border>
      </object>
      <object class="sizeritem">
        <object class="wxCheckBox" name="save">
          <label>save remote setting</label>
          <checked>1</checked>
        </object>
        <flag>wxLEFT</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <orient>wxHORIZONTAL</orient>
          <object class="sizeritem">
            <object class="wxButton" name="ok">
              <label>Ok</label>
            </object>
            <flag>wxALL</flag>
            <border>3</border>
          </object>
          <object class="sizeritem">
            <object class="wxButton" name="cancel">
              <label>Cancel</label>
            </object>
            <flag>wxALL</flag>
            <border>3</border>
          </object>
        </object>
        <flag>wxALL|wxALIGN_RIGHT</flag>
        <border>3</border>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/configremote/configremote_xrc', configremote_xrc)
    __res.Load('memory:XRC/configremote/configremote_xrc')

