# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res






# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    configglobal_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxPropertySheetDialog">
    <object class="propertysheetpage">
      <object class="wxPanel" name="Global">
        <object class="wxStaticBox">
          <label>Global configure</label>
        </object>
        <object class="wxGridSizer">
          <rows>2</rows>
          <cols>2</cols>
          <object class="sizeritem">
            <object class="wxStaticText">
              <label>Local project root</label>
            </object>
          </object>
          <object class="sizeritem">
            <object class="wxComboBox">
              <content>
                <item>C:\Home_Ishikura\docs/Nagara/local-root</item>
              </content>
              <selection>1</selection>
            </object>
          </object>
          <object class="sizeritem">
            <object class="wxStaticText">
              <label>Remote project root</label>
            </object>
          </object>
          <object class="sizeritem">
            <object class="wxComboBox">
              <content>
                <item>/home/ishikura/Nagara/projects</item>
              </content>
            </object>
          </object>
        </object>
      </object>
      <label>Global configure</label>
    </object>
    <object class="propertysheetpage">
      <object class="wxPanel" name="Connection"/>
      <label>remote settings</label>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/configglobal/configglobal_xrc', configglobal_xrc)
    __res.Load('memory:XRC/configglobal/configglobal_xrc')

