class_name: ConfigManagerModel
events:
    - init
    - update

getsets:
    jobname: jobname

properties:

enables:
    - is_selected

methods:
    - create_location
    - delete_location
    - get_loc_view_list
    - get_loc_name_list

