# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcAmberView(wx.Panel):
#!XRCED:begin-block:xrcAmberView.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcAmberView.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PrePanel()
        self.PreCreate(pre)
        get_resources().LoadOnPanel(pre, parent, "AmberView")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    amberview_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxPanel" name="AmberView">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxStaticText">
          <label>Amber settings</label>
        </object>
        <option>0</option>
        <flag>wxEXPAND</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>amber input file :</label>
                </object>
                <option>1</option>
                <flag>wxEXPAND</flag>
              </object>
              <object class="sizeritem">
                <object class="wxFilePickerCtrl" name="input_file"/>
                <option>2</option>
                <flag>wxEXPAND</flag>
              </object>
              <orient>wxHORIZONTAL</orient>
            </object>
            <option>1</option>
            <flag>wxALL|wxEXPAND</flag>
            <border>3</border>
          </object>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>prmtop file(*.prmtop) : </label>
                </object>
                <option>1</option>
                <flag>wxEXPAND</flag>
              </object>
              <object class="sizeritem">
                <object class="wxFilePickerCtrl" name="prmtop_file"/>
                <option>2</option>
                <flag>wxEXPAND</flag>
              </object>
              <orient>wxHORIZONTAL</orient>
            </object>
            <option>1</option>
            <flag>wxALL|wxEXPAND</flag>
            <border>3</border>
          </object>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>amber restart file : </label>
                </object>
                <option>1</option>
                <flag>wxEXPAND</flag>
              </object>
              <object class="sizeritem">
                <object class="wxFilePickerCtrl" name="ip_restart_file"/>
                <option>2</option>
                <flag>wxEXPAND</flag>
              </object>
              <orient>wxHORIZONTAL</orient>
            </object>
            <option>1</option>
            <flag>wxALL|wxEXPAND</flag>
            <border>3</border>
          </object>
          <label>Select Amber setting files to input</label>
          <orient>wxVERTICAL</orient>
        </object>
        <option>0</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <object class="sizeritem">
            <object class="wxButton" name="run_remote_config">
              <label>show setting dialog</label>
            </object>
            <flag>wxALL|wxALIGN_CENTRE</flag>
            <border>5</border>
          </object>
          <label>Other settings</label>
          <orient>wxVERTICAL</orient>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <object class="sizeritem">
            <object class="wxButton" name="run_amber">
              <label>run</label>
            </object>
            <option>0</option>
            <flag>wxALL</flag>
            <border>5</border>
          </object>
          <object class="sizeritem">
            <object class="wxGauge" name="run_guage"/>
            <option>1</option>
            <flag>wxALL|wxEXPAND</flag>
            <border>5</border>
          </object>
          <label>Run amber</label>
          <orient>wxHORIZONTAL</orient>
        </object>
        <option>0</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <label>Output operations</label>
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>amber log file : </label>
                </object>
                <option>2</option>
              </object>
              <object class="sizeritem">
                <object class="wxComboBox" name="log_file"/>
                <option>3</option>
              </object>
              <orient>wxHORIZONTAL</orient>
              <object class="sizeritem">
                <object class="wxButton" name="log_file_dialog">
                  <label>save as ...</label>
                  <style>wxSUNKEN_BORDER|wxNO_BORDER|wxNO_BORDER</style>
                </object>
                <option>1</option>
              </object>
            </object>
            <option>1</option>
            <flag>wxALL|wxEXPAND</flag>
            <border>3</border>
          </object>
          <object class="sizeritem">
            <object class="wxButton" name="show_log_file">
              <label>show amber log file</label>
            </object>
            <option>0</option>
            <flag>wxBOTTOM|wxALL|wxALIGN_RIGHT</flag>
            <border>5</border>
          </object>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>amber restart file : </label>
                </object>
                <option>2</option>
              </object>
              <object class="sizeritem">
                <object class="wxComboBox" name="op_restart_file"/>
                <option>3</option>
              </object>
              <object class="sizeritem">
                <object class="wxButton" name="op_restart_dialog">
                  <label>save as ...</label>
                  <style>wxSUNKEN_BORDER|wxNO_BORDER|wxNO_BORDER</style>
                </object>
                <option>1</option>
              </object>
              <orient>wxHORIZONTAL</orient>
            </object>
            <option>1</option>
            <flag>wxALL</flag>
            <border>3</border>
          </object>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>coordinate trajectory file : </label>
                </object>
                <option>2</option>
              </object>
              <object class="sizeritem">
                <object class="wxComboBox" name="crds_file"/>
                <option>3</option>
              </object>
              <object class="sizeritem">
                <object class="wxButton" name="crds_file_dialog">
                  <label>save as ...</label>
                  <style>wxSUNKEN_BORDER|wxNO_BORDER|wxNO_BORDER</style>
                </object>
                <option>1</option>
              </object>
              <orient>wxHORIZONTAL</orient>
            </object>
            <option>1</option>
            <flag>wxALL</flag>
            <border>3</border>
          </object>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>velocity trajectory file : </label>
                </object>
                <option>2</option>
              </object>
              <object class="sizeritem">
                <object class="wxComboBox" name="vels_file"/>
                <option>3</option>
              </object>
              <object class="sizeritem">
                <object class="wxButton" name="vels_file_dialog">
                  <label>save as ...</label>
                  <style>wxSUNKEN_BORDER|wxNO_BORDER|wxNO_BORDER</style>
                </object>
                <option>1</option>
              </object>
              <orient>wxHORIZONTAL</orient>
            </object>
            <option>1</option>
            <flag>wxALL</flag>
            <border>3</border>
          </object>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>energy trajectory file : </label>
                </object>
                <option>2</option>
              </object>
              <object class="sizeritem">
                <object class="wxComboBox" name="enes_file"/>
                <option>3</option>
              </object>
              <object class="sizeritem">
                <object class="wxButton" name="enes_file_dialog">
                  <label>save as ...</label>
                  <style>wxSUNKEN_BORDER|wxNO_BORDER|wxNO_BORDER</style>
                </object>
                <option>1</option>
              </object>
              <orient>wxHORIZONTAL</orient>
            </object>
            <option>1</option>
            <flag>wxALL</flag>
            <border>3</border>
          </object>
          <object class="sizeritem">
            <object class="wxButton" name="save_output">
              <label>save outputs</label>
            </object>
            <flag>wxALL|wxALIGN_CENTRE</flag>
            <border>10</border>
          </object>
        </object>
        <option>0</option>
        <flag>wxALL|wxEXPAND|wxALIGN_RIGHT</flag>
        <border>5</border>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/amberview/amberview_xrc', amberview_xrc)
    __res.Load('memory:XRC/amberview/amberview_xrc')

