#######################################################
# 
# DockingWizard.py
# Python implementation of the Class DockingWizard
# Generated by Enterprise Architect
# Created on:      18-6-2008 13:50:34
# Original author: ishikura
# 
#######################################################
from テストビュー.クライアントパッケージ.startDocking import startDocking
from テストビュー.クライアントパッケージ.runDocking import runDocking
from テストビュー.クライアントパッケージ.showDockingProcess import showDockingProcess
from テストビュー.クライアントパッケージ.FlowWizard import FlowWizard

class DockingWizard(FlowWizard):
    startDocking= startDocking()
    runDocking= runDocking()
    showDockingProcess= showDockingProcess()

    def testMethod():
        """This method is test.
    
           Keyword args:
           aa -- aa
           bb -- bb
        """
        a = 1
        b = 2
        c = "est"
       